name: my_app  # Replace with your app's name
description: A Flutter project for Trainer User Management.

publish_to: 'none' # Remove this line if you intend to publish the package.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11  # Update to the latest version as needed
  cupertino_icons: ^1.0.2  # Ensure this is included
  shared_preferences: ^2.0.15 # Add this line with the latest version
  table_calendar: ^3.0.5   # Or the latest version available
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  googleapis_auth: ^1.0.0
  googleapis:
  jose: ^0.3.4
  intl: ^0.19.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Or the latest version

flutter:
  uses-material-design: true
  assets:
    - assets/images/  # If you're using SVGs or other images
    - assets/fonts/    # Add this if you want to load all fonts in the folder
  fonts:
    - family: Digital
      fonts:
        - asset: assets/fonts/digital-7.ttf